name: Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with: 
          go-version: 1.21.x
      
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          args: "release --clean"
          version: latest
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
